# SITE CONFIGURATION
title: KANVAS ATELIER # your site title
author: Lucas Van Hooreweghe # You :P
description: > # Meta description of Homepage
  Ward is mega cool
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kanvasatelier.be" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Kanvas Atelier
  links:
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'BROEINEST', link: '/'}
  - {name: 'ATELIERS', link: '/ateliers'}
  - {name: 'CONTACT', link: '/contact'}

tagline: >
  Broeinest voor creativiteit in Deinze en omstreken
  

hero_img: posts/header-image.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: info@kanvasatelier.be # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: kanvasatelier # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_tag_manager: UA-123908133-1

service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
